# Generated by Django 5.2.15 on 2026-06-16 02:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('total_miles', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('total_days', models.PositiveSmallIntegerField(default=1)),
                ('fuel_stops_count', models.PositiveSmallIntegerField(default=0)),
                ('projected_cycle_used', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('cycle_available', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('route_polyline', models.JSONField(blank=True, default=list)),
                ('engine', models.CharField(choices=[('stub', 'Stub'), ('hos', 'HOS')], default='stub', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='trip_trippl_created_63074b_idx'), models.Index(fields=['status'], name='trip_trippl_status_1b617b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyLogSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('log_date', models.DateField()),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('total_miles_driving', models.DecimalField(decimal_places=1, max_digits=8)),
                ('truck_number', models.CharField(default='T-1042', max_length=32)),
                ('trailer_number', models.CharField(default='TR-8831', max_length=32)),
                ('shipper', models.CharField(blank=True, max_length=255)),
                ('commodity', models.CharField(blank=True, max_length=255)),
                ('total_off_duty', models.CharField(default='0:00', max_length=8)),
                ('total_sleeper', models.CharField(default='0:00', max_length=8)),
                ('total_driving', models.CharField(default='0:00', max_length=8)),
                ('total_on_duty', models.CharField(default='0:00', max_length=8)),
                ('recap_on_duty_today', models.DecimalField(decimal_places=1, max_digits=5)),
                ('recap_cycle_used', models.DecimalField(decimal_places=1, max_digits=5)),
                ('recap_cycle_available', models.DecimalField(decimal_places=1, max_digits=5)),
                ('trip_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sheets', to='trip.tripplan')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='LogSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('duty_status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty', 'On Duty (not driving)')], max_length=16)),
                ('start_minute', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(1439)])),
                ('end_minute', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('remark', models.CharField(blank=True, max_length=512)),
                ('log_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='trip.dailylogsheet')),
            ],
            options={
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['log_sheet', 'duty_status'], name='trip_logseg_log_she_a9b991_idx')],
                'constraints': [models.UniqueConstraint(fields=('log_sheet', 'sequence'), name='uniq_log_segment_sequence'), models.CheckConstraint(condition=models.Q(('end_minute__gt', models.F('start_minute'))), name='log_segment_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('stop_type', models.CharField(choices=[('start', 'Trip start'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('fuel', 'Fuel'), ('rest', 'Rest')], max_length=16)),
                ('label', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('occurred_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('trip_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trip.tripplan')),
            ],
            options={
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['trip_plan', 'stop_type'], name='trip_routes_trip_pl_549aba_idx')],
                'constraints': [models.UniqueConstraint(fields=('trip_plan', 'sequence'), name='uniq_route_stop_sequence')],
            },
        ),
        migrations.CreateModel(
            name='RouteLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('miles', models.DecimalField(decimal_places=1, max_digits=8)),
                ('trip_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='trip.tripplan')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('trip_plan', 'sequence'), name='uniq_route_leg_sequence')],
            },
        ),
        migrations.AddConstraint(
            model_name='dailylogsheet',
            constraint=models.UniqueConstraint(fields=('trip_plan', 'log_date'), name='uniq_log_sheet_date'),
        ),
        migrations.AddConstraint(
            model_name='dailylogsheet',
            constraint=models.UniqueConstraint(fields=('trip_plan', 'day_number'), name='uniq_log_sheet_day_number'),
        ),
    ]
