# Generated by Django 5.2.15 on 2026-06-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='assumptions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='route_instructions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
