# Generated by Django 5.2.15 on 2026-06-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_tripplan_assumptions_tripplan_route_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripplan',
            name='engine',
            field=models.CharField(choices=[('stub', 'Stub'), ('hos', 'HOS')], default='hos', max_length=16),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=16),
        ),
    ]
